//
// syscall_table.c
// By: Tristan Blaudez <tblaudez@student.codam.nl>
// Created: 15/09/2021 14:27:09
//

#include <linux/audit.h>
#include "strace.h"

static const t_syscall syscall_table_64[] = {
		{"read",                   LONG,  3, {UINT,  STR,   ULONG}},
		{"write",                  LONG,  3, {UINT,  STR,   ULONG}},
		{"open",                   INT,   3, {STR,   INT,   UINT}},
		{"close",                  INT,   1, {UINT}},
		{"stat",                   INT,   2, {STR,   PTR}},
		{"fstat",                  INT,   2, {UINT,  PTR}},
		{"lstat",                  INT,   2, {STR,   PTR}},
		{"poll",                   INT,   3, {PTR,   UINT,  INT}},
		{"lseek",                  LONG,  3, {UINT,  LONG,  UINT}},
		{"mmap",                   PTR,   6, {PTR,   ULONG, ULONG, ULONG, ULONG, ULONG}},
		{"mprotect",               INT,   3, {ULONG, ULONG, ULONG}},
		{"munmap",                 INT,   2, {ULONG, ULONG}},
		{"brk",                    PTR,   1, {PTR}},
		{"rt_sigaction",           LONG,  4, {INT,   PTR,   PTR,   ULONG}},
		{"rt_sigprocmask",         INT,   4, {INT,   PTR,   PTR,   ULONG}},
		{"rt_sigreturn",           LONG,  0, {}},
		{"ioctl",                  INT,   3, {UINT,  UINT,  ULONG}},
		{"pread64",                LONG,  4, {UINT,  STR,   ULONG, LONG}},
		{"pwrite64",               LONG,  4, {UINT,  STR,   ULONG, LONG}},
		{"readv",                  LONG,  3, {ULONG, PTR,   ULONG}},
		{"writev",                 LONG,  3, {ULONG, PTR,   ULONG}},
		{"access",                 INT,   2, {STR,   INT}},
		{"pipe",                   INT,   1, {PTR}},
		{"select",                 INT,   5, {INT,   PTR,   PTR,   PTR,   PTR}},
		{"sched_yield",            LONG,  0, {}},
		{"mremap",                 PTR,   5, {ULONG, ULONG, ULONG, ULONG, ULONG}},
		{"msync",                  INT,   3, {ULONG, ULONG, INT}},
		{"mincore",                INT,   3, {ULONG, ULONG, STR}},
		{"madvise",                INT,   3, {ULONG, ULONG, INT}},
		{"shmget",                 INT,   3, {INT,   ULONG, INT}},
		{"shmat",                  PTR,   3, {INT,   STR,   INT}},
		{"shmctl",                 INT,   3, {INT,   INT,   PTR}},
		{"dup",                    INT,   1, {UINT}},
		{"dup2",                   INT,   2, {UINT,  UINT}},
		{"pause",                  LONG,  0, {}},
		{"nanosleep",              INT,   2, {PTR,   PTR}},
		{"getitimer",              INT,   2, {INT,   PTR}},
		{"alarm",                  UINT,  1, {UINT}},
		{"setitimer",              INT,   3, {INT,   PTR,   PTR}},
		{"getpid",                 LONG,  0, {}},
		{"sendfile",               LONG,  4, {INT,   INT,   PTR,   ULONG}},
		{"socket",                 INT,   3, {INT,   INT,   INT}},
		{"connect",                INT,   3, {INT,   PTR,   INT}},
		{"accept",                 INT,   3, {INT,   PTR,   PTR}},
		{"sendto",                 LONG,  6, {INT,   PTR,   ULONG, UINT,  PTR,   INT}},
		{"recvfrom",               LONG,  6, {INT,   PTR,   ULONG, UINT,  PTR,   PTR}},
		{"sendmsg",                LONG,  3, {INT,   PTR,   UINT}},
		{"recvmsg",                LONG,  3, {INT,   PTR,   UINT}},
		{"shutdown",               INT,   2, {INT,   INT}},
		{"bind",                   INT,   3, {INT,   PTR,   INT}},
		{"listen",                 INT,   2, {INT,   INT}},
		{"getsockname",            INT,   3, {INT,   PTR,   PTR}},
		{"getpeername",            INT,   3, {INT,   PTR,   PTR}},
		{"socketpair",             INT,   4, {INT,   INT,   INT,   PTR}},
		{"setsockopt",             INT,   5, {INT,   INT,   INT,   STR,   INT}},
		{"getsockopt",             INT,   5, {INT,   INT,   INT,   STR,   PTR}},
		{"clone",                  INT,   5, {ULONG, ULONG, PTR,   PTR,   ULONG}},
		{"fork",                   LONG,  0, {}},
		{"vfork",                  LONG,  0, {}},
		{"execve",                 INT,   3, {STR,   ARRAY, ARRAY}},
		{"exit",                   VOID,  1, {INT}},
		{"wait4",                  INT,   4, {INT,   PTR,   INT,   PTR}},
		{"kill",                   INT,   2, {INT,   INT}},
		{"uname",                  INT,   1, {PTR}},
		{"semget",                 INT,   3, {INT,   INT,   INT}},
		{"semop",                  INT,   3, {INT,   PTR,   UINT}},
		{"semctl",                 INT,   4, {INT,   INT,   INT,   ULONG}},
		{"shmdt",                  INT,   1, {STR}},
		{"msgget",                 INT,   2, {INT,   INT}},
		{"msgsnd",                 INT,   4, {INT,   PTR,   ULONG, INT}},
		{"msgrcv",                 LONG,  5, {INT,   PTR,   ULONG, LONG,  INT}},
		{"msgctl",                 INT,   3, {INT,   INT,   PTR}},
		{"fcntl",                  INT,   3, {UINT,  UINT,  ULONG}},
		{"flock",                  INT,   2, {UINT,  UINT}},
		{"fsync",                  INT,   1, {UINT}},
		{"fdatasync",              INT,   1, {UINT}},
		{"truncate",               INT,   2, {STR,   LONG}},
		{"ftruncate",              INT,   2, {UINT,  ULONG}},
		{"getdents",               INT,   3, {UINT,  PTR,   UINT}},
		{"getcwd",                 STR,   2, {STR,   ULONG}},
		{"chdir",                  INT,   1, {STR}},
		{"fchdir",                 INT,   1, {UINT}},
		{"rename",                 INT,   2, {STR,   STR}},
		{"mkdir",                  INT,   2, {STR,   UINT}},
		{"rmdir",                  INT,   1, {STR}},
		{"creat",                  INT,   2, {STR,   UINT}},
		{"link",                   INT,   2, {STR,   STR}},
		{"unlink",                 INT,   1, {STR}},
		{"symlink",                INT,   2, {STR,   STR}},
		{"readlink",               LONG,  3, {STR,   STR,   INT}},
		{"chmod",                  INT,   2, {STR,   UINT}},
		{"fchmod",                 INT,   2, {UINT,  UINT}},
		{"chown",                  INT,   3, {STR,   UINT,  UINT}},
		{"fchown",                 INT,   3, {UINT,  UINT,  UINT}},
		{"lchown",                 INT,   3, {STR,   UINT,  UINT}},
		{"umask",                  UINT,  1, {INT}},
		{"gettimeofday",           INT,   2, {PTR,   PTR}},
		{"getrlimit",              INT,   2, {UINT,  PTR}},
		{"getrusage",              INT,   2, {INT,   PTR}},
		{"sysinfo",                INT,   1, {PTR}},
		{"times",                  ULONG, 1, {PTR}},
		{"ptrace",                 LONG,  4, {LONG,  LONG,  ULONG, ULONG}},
		{"getuid",                 LONG,  0, {}},
		{"syslog",                 INT,   3, {INT,   STR,   INT}},
		{"getgid",                 LONG,  0, {}},
		{"setuid",                 INT,   1, {UINT}},
		{"setgid",                 INT,   1, {UINT}},
		{"geteuid",                LONG,  0, {}},
		{"getegid",                LONG,  0, {}},
		{"setpgid",                INT,   2, {INT,   INT}},
		{"getppid",                LONG,  0, {}},
		{"getpgrp",                INT,   0, {}},
		{"setsid",                 LONG,  0, {}},
		{"setreuid",               INT,   2, {UINT,  UINT}},
		{"setregid",               INT,   2, {UINT,  UINT}},
		{"getgroups",              INT,   2, {INT,   PTR}},
		{"setgroups",              INT,   2, {INT,   PTR}},
		{"setresuid",              INT,   3, {UINT,  UINT,  UINT}},
		{"getresuid",              INT,   3, {PTR,   PTR,   PTR}},
		{"setresgid",              INT,   3, {UINT,  UINT,  UINT}},
		{"getresgid",              INT,   3, {PTR,   PTR,   PTR}},
		{"getpgid",                INT,   1, {INT}},
		{"setfsuid",               INT,   1, {UINT}},
		{"setfsgid",               INT,   1, {UINT}},
		{"getsid",                 INT,   1, {INT}},
		{"capget",                 INT,   2, {PTR,   PTR}},
		{"capset",                 INT,   2, {PTR,   PTR}},
		{"rt_sigpending",          LONG,  2, {PTR,   ULONG}},
		{"rt_sigtimedwait",        LONG,  4, {PTR,   PTR,   PTR,   ULONG}},
		{"rt_sigqueueinfo",        INT,   3, {INT,   INT,   PTR}},
		{"rt_sigsuspend",          LONG,  2, {PTR,   ULONG}},
		{"sigaltstack",            INT,   2, {PTR,   PTR}},
		{"utime",                  INT,   2, {STR,   PTR}},
		{"mknod",                  INT,   3, {STR,   UINT,  UINT}},
		{"uselib",                 INT,   1, {STR}},
		{"personality",            INT,   1, {UINT}},
		{"ustat",                  INT,   2, {UINT,  PTR}},
		{"statfs",                 INT,   2, {STR,   PTR}},
		{"fstatfs",                INT,   2, {UINT,  PTR}},
		{"sysfs",                  INT,   3, {INT,   ULONG, ULONG}},
		{"getpriority",            INT,   2, {INT,   INT}},
		{"setpriority",            INT,   3, {INT,   INT,   INT}},
		{"sched_setparam",         INT,   2, {INT,   PTR}},
		{"sched_getparam",         INT,   2, {INT,   PTR}},
		{"sched_setscheduler",     INT,   3, {INT,   INT,   PTR}},
		{"sched_getscheduler",     INT,   1, {INT}},
		{"sched_get_priority_max", INT,   1, {INT}},
		{"sched_get_priority_min", INT,   1, {INT}},
		{"sched_rr_get_INTerval",  INT,   2, {INT,   PTR}},
		{"mlock",                  INT,   2, {ULONG, ULONG}},
		{"munlock",                INT,   2, {ULONG, ULONG}},
		{"mlockall",               INT,   1, {INT}},
		{"munlockall",             LONG,  0, {}},
		{"vhangup",                LONG,  0, {}},
		{"modify_ldt",             INT,   3, {INT,   PTR,   ULONG}},
		{"pivot_root",             INT,   2, {STR,   STR}},
		{"_sysctl",                INT,   1, {PTR}},
		{"prctl",                  INT,   5, {INT,   ULONG, ULONG, ULONG, ULONG}},
		{"arch_prctl",             INT,   3, {PTR,   INT,   PTR}},
		{"adjtimex",               INT,   1, {PTR}},
		{"setrlimit",              INT,   2, {UINT,  PTR}},
		{"chroot",                 INT,   1, {STR}},
		{"sync",                   LONG,  0, {}},
		{"acct",                   INT,   1, {STR}},
		{"settimeofday",           INT,   2, {PTR,   PTR}},
		{"mount",                  INT,   5, {STR,   STR,   STR,   ULONG, PTR}},
		{"umount2",                INT,   2, {STR,   INT}},
		{"swapon",                 INT,   2, {STR,   INT}},
		{"swapoff",                INT,   1, {STR}},
		{"reboot",                 INT,   4, {INT,   INT,   UINT,  PTR}},
		{"sethostname",            INT,   2, {STR,   INT}},
		{"setdomainname",          INT,   2, {STR,   INT}},
		{"iopl",                   INT,   1, {UINT}},
		{"ioperm",                 INT,   3, {ULONG, ULONG, INT}},
		{"create_module",          ULONG, 0, {}},
		{"init_module",            INT,   3, {PTR,   ULONG, STR}},
		{"delete_module",          INT,   2, {STR,   UINT}},
		{"get_kernel_syms",        INT,   0, {}},
		{"query_module",           INT,   0, {}},
		{"quotactl",               INT,   4, {UINT,  STR,   UINT,  PTR}},
		{"nfsservctl",             LONG,  0, {}},
		{"getpmsg",                LONG,  0, {}},
		{"putpmsg",                LONG,  0, {}},
		{"afs_syscall",            LONG,  0, {}},
		{"tuxcall",                LONG,  0, {}},
		{"security",               LONG,  0, {}},
		{"gettid",                 LONG,  0, {}},
		{"readahead",              LONG,  3, {INT,   LONG,  ULONG}},
		{"setxattr",               INT,   5, {STR,   STR,   PTR,   ULONG, INT}},
		{"lsetxattr",              INT,   5, {STR,   STR,   PTR,   ULONG, INT}},
		{"fsetxattr",              INT,   5, {INT,   STR,   PTR,   ULONG, INT}},
		{"getxattr",               LONG,  4, {STR,   STR,   PTR,   ULONG}},
		{"lgetxattr",              LONG,  4, {STR,   STR,   PTR,   ULONG}},
		{"fgetxattr",              LONG,  4, {INT,   STR,   PTR,   ULONG}},
		{"listxattr",              LONG,  3, {STR,   STR,   ULONG}},
		{"llistxattr",             LONG,  3, {STR,   STR,   ULONG}},
		{"flistxattr",             LONG,  3, {INT,   STR,   ULONG}},
		{"removexattr",            INT,   2, {STR,   STR}},
		{"lremovexattr",           INT,   2, {STR,   STR}},
		{"fremovexattr",           INT,   2, {INT,   STR}},
		{"tkill",                  INT,   2, {INT,   INT}},
		{"time",                   ULONG, 1, {PTR}},
		{"futex",                  INT,   6, {PTR,   INT,   UINT,  PTR,   PTR,   UINT}},
		{"sched_setaffinity",      INT,   3, {INT,   UINT,  PTR}},
		{"sched_getaffinity",      INT,   3, {INT,   UINT,  PTR}},
		{"set_thread_area",        INT,   1, {PTR}},
		{"io_setup",               INT,   2, {UINT,  PTR}},
		{"io_destroy",             INT,   1, {ULONG}},
		{"io_getevents",           INT,   5, {ULONG, LONG,  LONG,  PTR,   PTR}},
		{"io_submit",              INT,   3, {ULONG, LONG,  PTR}},
		{"io_cancel",              INT,   3, {ULONG, PTR,   PTR}},
		{"get_thread_area",        INT,   1, {PTR}},
		{"lookup_dcookie",         INT,   3, {ULONG, STR,   ULONG}},
		{"epoll_create",           INT,   1, {INT}},
		{"epoll_ctl_old",          LONG,  0, {}},
		{"epoll_wait_old",         LONG,  0, {}},
		{"remap_file_pages",       INT,   5, {ULONG, ULONG, ULONG, ULONG, ULONG}},
		{"getdents64",             INT,   3, {UINT,  PTR,   UINT}},
		{"set_tid_address",        LONG,  1, {PTR}},
		{"restart_syscall",        LONG,  0, {}},
		{"semtimedop",             INT,   4, {INT,   PTR,   UINT,  PTR}},
		{"fadvise64",              LONG,  4, {INT,   LONG,  ULONG, INT}},
		{"timer_create",           INT,   3, {INT,   PTR,   PTR}},
		{"timer_settime",          INT,   4, {INT,   INT,   PTR,   PTR}},
		{"timer_gettime",          INT,   2, {INT,   PTR}},
		{"timer_getoverrun",       INT,   1, {INT}},
		{"timer_delete",           INT,   1, {INT}},
		{"clock_settime",          INT,   2, {INT,   PTR}},
		{"clock_gettime",          INT,   2, {INT,   PTR}},
		{"clock_getres",           INT,   2, {INT,   PTR}},
		{"clock_nanosleep",        INT,   4, {INT,   INT,   PTR,   PTR}},
		{"exit_group",             VOID,  1, {INT}},
		{"epoll_wait",             INT,   4, {INT,   PTR,   INT,   INT}},
		{"epoll_ctl",              INT,   4, {INT,   INT,   INT,   PTR}},
		{"tgkill",                 INT,   3, {INT,   INT,   INT}},
		{"utimes",                 INT,   2, {STR,   PTR}},
		{"vserver",                LONG,  0, {}},
		{"mbind",                  LONG,  6, {ULONG, ULONG, ULONG, PTR,   ULONG, UINT}},
		{"set_mempolicy",          LONG,  3, {INT,   PTR,   ULONG}},
		{"get_mempolicy",          LONG,  5, {PTR,   PTR,   ULONG, ULONG, ULONG}},
		{"mq_open",                ULONG, 4, {STR,   INT,   UINT,  PTR}},
		{"mq_unlink",              INT,   1, {STR}},
		{"mq_timedsend",           INT,   5, {INT,   STR,   ULONG, UINT,  PTR}},
		{"mq_timedreceive",        LONG,  5, {INT,   STR,   ULONG, PTR,   PTR}},
		{"mq_notify",              INT,   2, {INT,   PTR}},
		{"mq_getsetattr",          INT,   3, {INT,   PTR,   PTR}},
		{"kexec_load",             LONG,  4, {ULONG, ULONG, PTR,   ULONG}},
		{"waitid",                 INT,   5, {INT,   INT,   PTR,   INT,   PTR}},
		{"add_key",                INT,   5, {STR,   STR,   PTR,   ULONG, INT}},
		{"request_key",            INT,   4, {STR,   STR,   STR,   INT}},
		{"keyctl",                 LONG,  5, {INT,   ULONG, ULONG, ULONG, ULONG}},
		{"ioprio_set",             INT,   3, {INT,   INT,   INT}},
		{"ioprio_get",             INT,   2, {INT,   INT}},
		{"inotify_init",           LONG,  0, {}},
		{"inotify_add_watch",      INT,   3, {INT,   STR,   UINT}},
		{"inotify_rm_watch",       INT,   2, {INT,   INT}},
		{"migrate_pages",          LONG,  4, {INT,   ULONG, PTR,   PTR}},
		{"openat",                 INT,   4, {INT,   STR,   INT,   UINT}},
		{"mkdirat",                INT,   3, {INT,   STR,   UINT}},
		{"mknodat",                INT,   4, {INT,   STR,   UINT,  UINT}},
		{"fchownat",               INT,   5, {INT,   STR,   UINT,  UINT,  INT}},
		{"futimesat",              INT,   3, {INT,   STR,   PTR}},
		{"newfstatat",             LONG,  4, {INT,   STR,   PTR,   INT}},
		{"unlinkat",               INT,   3, {INT,   STR,   INT}},
		{"renameat",               INT,   4, {INT,   STR,   INT,   STR}},
		{"linkat",                 INT,   5, {INT,   STR,   INT,   STR,   INT}},
		{"symlinkat",              INT,   3, {STR,   INT,   STR}},
		{"readlinkat",             LONG,  4, {INT,   STR,   STR,   INT}},
		{"fchmodat",               INT,   3, {INT,   STR,   UINT}},
		{"faccessat",              INT,   3, {INT,   STR,   INT}},
		{"pselect6",               LONG,  6, {INT,   PTR,   PTR,   PTR,   PTR,   PTR}},
		{"ppoll",                  INT,   5, {PTR,   UINT,  PTR,   PTR,   ULONG}},
		{"unshare",                INT,   1, {ULONG}},
		{"set_robust_list",        LONG,  2, {PTR,   ULONG}},
		{"get_robust_list",        LONG,  3, {INT,   PTR,   PTR}},
		{"splice",                 LONG,  6, {INT,   PTR,   INT,   PTR,   ULONG, UINT}},
		{"tee",                    LONG,  4, {INT,   INT,   ULONG, UINT}},
		{"sync_file_range",        INT,   4, {INT,   LONG,  LONG,  UINT}},
		{"vmsplice",               LONG,  4, {INT,   PTR,   ULONG, UINT}},
		{"move_pages",             LONG,  6, {INT,   ULONG, PTR,   PTR,   PTR,   INT}},
		{"utimensat",              INT,   4, {INT,   STR,   PTR,   INT}},
		{"epoll_pwait",            INT,   6, {INT,   PTR,   INT,   INT,   PTR,   ULONG}},
		{"signalfd",               INT,   3, {INT,   PTR,   ULONG}},
		{"timerfd_create",         INT,   2, {INT,   INT}},
		{"eventfd",                INT,   1, {UINT}},
		{"fallocate",              INT,   4, {INT,   INT,   LONG,  LONG}},
		{"timerfd_settime",        INT,   4, {INT,   INT,   PTR,   PTR}},
		{"timerfd_gettime",        INT,   2, {INT,   PTR}},
		{"accept4",                INT,   4, {INT,   PTR,   PTR,   INT}},
		{"signalfd4",              LONG,  4, {INT,   PTR,   ULONG, INT}},
		{"eventfd2",               LONG,  2, {UINT,  INT}},
		{"epoll_create1",          INT,   1, {INT}},
		{"dup3",                   INT,   3, {UINT,  UINT,  INT}},
		{"pipe2",                  INT,   2, {PTR,   INT}},
		{"inotify_init1",          INT,   1, {INT}},
		{"preadv",                 LONG,  5, {ULONG, PTR,   ULONG, ULONG, ULONG}},
		{"pwritev",                LONG,  5, {ULONG, PTR,   ULONG, ULONG, ULONG}},
		{"rt_tgsigqueueinfo",      INT,   4, {INT,   INT,   INT,   PTR}},
		{"perf_event_open",        INT,   5, {PTR,   INT,   INT,   INT,   ULONG}},
		{"recvmmsg",               INT,   5, {INT,   PTR,   UINT,  UINT,  PTR}},
		{"fanotify_init",          INT,   2, {UINT,  UINT}},
		{"fanotify_mark",          INT,   5, {INT,   UINT,  ULONG, INT,   STR}},
		{"prlimit64",              LONG,  4, {INT,   UINT,  PTR,   PTR}},
		{"name_to_handle_at",      INT,   5, {INT,   STR,   PTR,   PTR,   INT}},
		{"open_by_handle_at",      INT,   3, {INT,   PTR,   INT}},
		{"clock_adjtime",          LONG,  2, {INT,   PTR}},
		{"syncfs",                 INT,   1, {INT}},
		{"sendmmsg",               INT,   4, {INT,   PTR,   UINT,  UINT}},
		{"setns",                  INT,   2, {INT,   INT}},
		{"getcpu",                 INT,   3, {PTR,   PTR,   PTR}},
		{"process_vm_readv",       LONG,  6, {INT,   PTR,   ULONG, PTR,   ULONG, ULONG}},
		{"process_vm_writev",      LONG,  6, {INT,   PTR,   ULONG, PTR,   ULONG, ULONG}},
		{"kcmp",                   INT,   5, {INT,   INT,   INT,   ULONG, ULONG}},
		{"finit_module",           INT,   3, {INT,   STR,   INT}},
		{"sched_setattr",          INT,   3, {INT,   PTR,   UINT}},
		{"sched_getattr",          INT,   4, {INT,   PTR,   UINT,  UINT}},
		{"renameat2",              INT,   5, {INT,   STR,   INT,   STR,   UINT}},
		{"seccomp",                INT,   3, {UINT,  UINT,  PTR}},
		{"getrandom",              LONG,  3, {STR,   ULONG, UINT}},
		{"memfd_create",           INT,   2, {STR,   UINT}},
		{"kexec_file_load",        LONG,  5, {INT,   INT,   ULONG, STR,   ULONG}},
		{"bpf",                    INT,   3, {INT,   PTR,   UINT}},
		{"execveat",               INT,   5, {INT,   STR,   ARRAY, ARRAY, INT}},
		{"userfaultfd",            INT,   1, {INT}},
		{"membarrier",             INT,   2, {INT,   INT}},
		{"mlock2",                 INT,   3, {ULONG, ULONG, INT}},
		{"copy_file_range",        LONG,  6, {INT,   PTR,   INT,   PTR,   ULONG, UINT}},
		{"preadv2",                LONG,  6, {ULONG, PTR,   ULONG, ULONG, ULONG, INT}},
		{"pwritev2",               LONG,  6, {ULONG, PTR,   ULONG, ULONG, ULONG, INT}},
		{"pkey_mprotect",          INT,   4, {ULONG, ULONG, ULONG, INT}},
		{"pkey_alloc",             INT,   2, {ULONG, ULONG}},
		{"pkey_free",              INT,   1, {INT}},
		{"statx",                  INT,   5, {INT,   STR,   UINT,  UINT,  PTR}}
};

static const t_syscall syscall_table_32[] = {
		{"restart_syscall",        INT,   0, {}},
		{"exit",                   VOID,  1, {INT}},
		{"fork",                   INT,   0, {}},
		{"read",                   LONG,  3, {UINT,  STR,   ULONG}},
		{"write",                  LONG,  3, {UINT,  STR,   ULONG}},
		{"open",                   INT,   3, {STR,   INT,   UINT}},
		{"close",                  INT,   1, {UINT}},
		{"waitpid",                INT,   3, {INT,   PTR,   INT}},
		{"creat",                  INT,   2, {STR,   UINT}},
		{"link",                   INT,   2, {STR,   STR}},
		{"unlink",                 INT,   1, {STR}},
		{"execve",                 INT,   3, {STR,   ARRAY, ARRAY}},
		{"chdir",                  INT,   1, {STR}},
		{"time",                   ULONG, 1, {PTR}},
		{"mknod",                  INT,   3, {STR,   UINT,  UINT}},
		{"chmod",                  INT,   2, {STR,   UINT}},
		{"lchown",                 INT,   3, {STR,   UINT,  UINT}},
		{"break",                  VOID,  0, {}},
		{"oldstat",                INT,   2, {STR,   PTR}},
		{"lseek",                  LONG,  3, {UINT,  LONG,  UINT}},
		{"getpid",                 LONG,  0, {}},
		{"mount",                  INT,   5, {STR,   STR,   STR,   ULONG, PTR}},
		{"umount",                 INT,   2, {STR,   INT}},
		{"setuid",                 INT,   1, {UINT}},
		{"getuid",                 INT,   0, {}},
		{"stime",                  INT,   1, {PTR}},
		{"ptrace",                 LONG,  4, {LONG,  LONG,  ULONG, ULONG}},
		{"alarm",                  UINT,  1, {UINT}},
		{"oldfstat",               INT,   2, {INT,   PTR}},
		{"pause",                  INT,   0, {}},
		{"utime",                  INT,   2, {STR,   PTR}},
		{"stty",                   VOID,  0, {}},
		{"gtty",                   VOID,  0, {}},
		{"access",                 INT,   2, {STR,   INT}},
		{"nice",                   INT,   1, {INT}},
		{"ftime",                  INT,   0, {}},
		{"sync",                   VOID,  0, {}},
		{"kill",                   INT,   2, {INT,   INT}},
		{"rename",                 INT,   2, {STR,   STR}},
		{"mkdir",                  INT,   2, {STR,   UINT}},
		{"rmdir",                  INT,   1, {STR}},
		{"dup",                    INT,   1, {UINT}},
		{"pipe",                   INT,   1, {PTR}},
		{"times",                  ULONG, 1, {PTR}},
		{"prof",                   VOID,  0, {}},
		{"brk",                    INT,   1, {PTR}},
		{"setgid",                 INT,   1, {UINT}},
		{"getgid",                 INT,   0, {}},
		{"signal",                 PTR,   2, {INT,   PTR}},
		{"geteuid",                INT,   0, {}},
		{"getegid",                INT,   0, {}},
		{"acct",                   INT,   1, {STR}},
		{"umount2",                INT,   2, {STR,   INT}},
		{"lock",                   VOID,  0, {}},
		{"ioctl",                  INT,   3, {UINT,  UINT,  ULONG}},
		{"fcntl",                  INT,   3, {UINT,  UINT,  ULONG}},
		{"mpx",                    VOID,  0, {}},
		{"setpgid",                INT,   2, {INT,   INT}},
		{"ulimit",                 LONG,  0, {}},
		{"oldolduname",            INT,   1, {PTR}},
		{"umask",                  UINT,  1, {INT}},
		{"chroot",                 INT,   1, {STR}},
		{"ustat",                  INT,   2, {UINT,  PTR}},
		{"dup2",                   INT,   2, {UINT,  UINT}},
		{"getppid",                INT,   0, {}},
		{"getpgrp",                INT,   0, {}},
		{"setsid",                 INT,   0, {}},
		{"sigaction",              INT,   3, {INT,   PTR,   PTR}},
		{"sgetmask",               LONG,  0, {}},
		{"ssetmask",               LONG,  1, {INT}},
		{"setreuid",               INT,   2, {UINT,  UINT}},
		{"setregid",               INT,   2, {UINT,  UINT}},
		{"sigsuspend",             INT,   3, {INT,   INT,   ULONG}},
		{"sigpending",             INT,   1, {PTR}},
		{"sethostname",            INT,   2, {STR,   INT}},
		{"setrlimit",              INT,   2, {UINT,  PTR}},
		{"getrlimit",              INT,   2, {UINT,  PTR}},
		{"getrusage",              INT,   2, {INT,   PTR}},
		{"gettimeofday",           INT,   2, {PTR,   PTR}},
		{"settimeofday",           INT,   2, {PTR,   PTR}},
		{"getgroups",              INT,   2, {INT,   PTR}},
		{"setgroups",              INT,   2, {INT,   PTR}},
		{"select",                 INT,   5, {INT,   PTR,   PTR,   PTR,   PTR}},
		{"symlink",                INT,   2, {STR,   STR}},
		{"oldlstat",               INT,   2, {STR,   PTR}},
		{"readlink",               LONG,  3, {STR,   STR,   INT}},
		{"uselib",                 INT,   1, {STR}},
		{"swapon",                 INT,   2, {STR,   INT}},
		{"reboot",                 INT,   4, {INT,   INT,   UINT,  PTR}},
		{"readdir",                INT,   3, {INT,   PTR,   UINT}},
		{"mmap",                   PTR,   6, {PTR,   UINT,  INT,   INT,   INT,   LONG}},
		{"munmap",                 INT,   2, {ULONG, ULONG}},
		{"truncate",               INT,   2, {STR,   LONG}},
		{"ftruncate",              INT,   2, {UINT,  ULONG}},
		{"fchmod",                 INT,   2, {UINT,  UINT}},
		{"fchown",                 INT,   3, {UINT,  UINT,  UINT}},
		{"getpriority",            INT,   2, {INT,   INT}},
		{"setpriority",            INT,   3, {INT,   INT,   INT}},
		{"profil",                 INT,   0, {}},
		{"statfs",                 INT,   2, {STR,   PTR}},
		{"fstatfs",                INT,   2, {UINT,  PTR}},
		{"ioperm",                 INT,   3, {ULONG, ULONG, INT}},
		{"socketcall",             INT,   2, {INT,   PTR}},
		{"syslog",                 INT,   3, {INT,   STR,   INT}},
		{"setitimer",              INT,   3, {INT,   PTR,   PTR}},
		{"getitimer",              INT,   2, {INT,   PTR}},
		{"stat",                   INT,   2, {STR,   PTR}},
		{"lstat",                  INT,   2, {STR,   PTR}},
		{"fstat",                  INT,   2, {UINT,  PTR}},
		{"olduname",               INT,   1, {PTR}},
		{"iopl",                   INT,   1, {INT}},
		{"vhangup",                INT,   0, {}},
		{"idle",                   INT,   0, {}},
		{"vm86old",                INT,   1, {PTR}},
		{"wait4",                  INT,   4, {INT,   PTR,   INT,   PTR}},
		{"swapoff",                INT,   1, {STR}},
		{"sysinfo",                INT,   1, {PTR}},
		{"ipc",                    INT,   6, {UINT,  INT,   ULONG, ULONG, PTR,   LONG}},
		{"fsync",                  INT,   1, {UINT}},
		{"sigreturn",              INT,   0, {}},
		{"clone",                  INT,   5, {ULONG, ULONG, PTR,   PTR,   ULONG}},
		{"setdomainname",          INT,   2, {STR,   INT}},
		{"uname",                  INT,   1, {PTR}},
		{"modify_ldt",             INT,   3, {INT,   PTR,   ULONG}},
		{"adjtimex",               INT,   1, {PTR}},
		{"mprotect",               INT,   3, {ULONG, ULONG, ULONG}},
		{"sigprocmask",            INT,   3, {INT,   PTR,   PTR}},
		{"create_module",          ULONG, 2, {STR,   ULONG}},
		{"init_module",            INT,   3, {PTR,   ULONG, STR}},
		{"delete_module",          INT,   2, {STR,   UINT}},
		{"get_kernel_syms",        INT,   1, {PTR}},
		{"quotactl",               INT,   4, {UINT,  STR,   UINT,  PTR}},
		{"getpgid",                INT,   1, {INT}},
		{"fchdir",                 INT,   1, {UINT}},
		{"bdflush",                INT,   2, {INT,   LONG}},
		{"sysfs",                  INT,   3, {INT,   ULONG, ULONG}},
		{"personality",            INT,   1, {UINT}},
		{"afs_syscall",            VOID,  0, {}},
		{"setfsuid",               INT,   1, {UINT}},
		{"setfsgid",               INT,   1, {UINT}},
		{"_llseek",                INT,   5, {UINT,  ULONG, ULONG, LONG,  UINT}},
		{"getdents",               INT,   3, {UINT,  PTR,   UINT}},
		{"_newselect",             INT,   5, {INT,   PTR,   PTR,   PTR,   PTR}},
		{"flock",                  INT,   2, {UINT,  UINT}},
		{"msync",                  INT,   3, {ULONG, ULONG, INT}},
		{"readv",                  LONG,  3, {ULONG, PTR,   ULONG}},
		{"writev",                 LONG,  3, {ULONG, PTR,   ULONG}},
		{"getsid",                 INT,   1, {INT}},
		{"fdatasync",              INT,   1, {UINT}},
		{"_sysctl",                INT,   1, {PTR}},
		{"mlock",                  INT,   2, {ULONG, ULONG}},
		{"munlock",                INT,   2, {ULONG, ULONG}},
		{"mlockall",               INT,   1, {INT}},
		{"munlockall",             INT,   0, {}},
		{"sched_setparam",         INT,   2, {INT,   PTR}},
		{"sched_getparam",         INT,   2, {INT,   PTR}},
		{"sched_setscheduler",     INT,   3, {INT,   INT,   PTR}},
		{"sched_getscheduler",     INT,   1, {INT}},
		{"sched_yield",            INT,   0, {}},
		{"sched_get_priority_max", INT,   1, {INT}},
		{"sched_get_priority_min", INT,   1, {INT}},
		{"sched_rr_get_interval",  INT,   2, {INT,   PTR}},
		{"nanosleep",              INT,   2, {PTR,   PTR}},
		{"mremap",                 PTR,   5, {ULONG, ULONG, ULONG, ULONG, ULONG}},
		{"setresuid",              INT,   3, {UINT,  UINT,  UINT}},
		{"getresuid",              INT,   3, {PTR,   PTR,   PTR}},
		{"vm86",                   INT,   2, {ULONG, PTR}},
		{"query_module",           INT,   5, {STR,   INT,   PTR,   ULONG, ULONG}},
		{"poll",                   INT,   3, {PTR,   UINT,  INT}},
		{"nfsservctl",             LONG,  3, {INT,   PTR,   PTR}},
		{"setresgid",              INT,   3, {UINT,  UINT,  UINT}},
		{"getresgid",              INT,   3, {PTR,   PTR,   PTR}},
		{"prctl",                  INT,   5, {INT,   ULONG, ULONG, ULONG, ULONG}},
		{"rt_sigreturn",           INT,   0, {}},
		{"rt_sigaction",           INT,   4, {INT,   PTR,   PTR,   ULONG}},
		{"rt_sigprocmask",         INT,   4, {INT,   PTR,   PTR,   ULONG}},
		{"rt_sigpending",          INT,   2, {PTR,   ULONG}},
		{"rt_sigtimedwait",        INT,   4, {PTR,   PTR,   PTR,   ULONG}},
		{"rt_sigqueueinfo",        INT,   3, {INT,   INT,   PTR}},
		{"rt_sigsuspend",          INT,   2, {PTR,   ULONG}},
		{"pread64",                LONG,  4, {UINT,  STR,   ULONG, LONG}},
		{"pwrite64",               LONG,  4, {UINT,  STR,   ULONG, LONG}},
		{"chown",                  INT,   3, {STR,   UINT,  UINT}},
		{"getcwd",                 STR,   2, {STR,   ULONG}},
		{"capget",                 INT,   2, {PTR,   PTR}},
		{"capset",                 INT,   2, {PTR,   PTR}},
		{"sigaltstack",            INT,   2, {PTR,   PTR}},
		{"sendfile",               LONG,  4, {INT,   INT,   PTR,   ULONG}},
		{"getpmsg",                VOID,  0, {}},
		{"putpmsg",                VOID,  0, {}},
		{"vfork",                  INT,   0, {}},
		{"ugetrlimit",             INT,   2, {INT,   PTR}},
		{"mmap2",                  PTR,   6, {PTR,   ULONG, INT,   INT,   INT,   LONG}},
		{"truncate64",             INT,   2, {STR,   LONG}},
		{"ftruncate64",            INT,   2, {UINT,  LONG}},
		{"stat64",                 INT,   2, {STR,   PTR}},
		{"lstat64",                INT,   2, {STR,   PTR}},
		{"fstat64",                INT,   2, {ULONG, PTR}},
		{"lchown32",               INT,   3, {STR,   INT,   INT}},
		{"getuid32",               INT,   0, {}},
		{"getgid32",               INT,   0, {}},
		{"geteuid32",              INT,   0, {}},
		{"getegid32",              INT,   0, {}},
		{"setreuid32",             INT,   2, {INT,   INT}},
		{"setregid32",             INT,   2, {INT,   INT}},
		{"getgroups32",            INT,   2, {INT,   PTR}},
		{"setgroups32",            INT,   2, {LONG,  PTR}},
		{"fchown32",               INT,   3, {INT,   INT,   INT}},
		{"setresuid32",            INT,   3, {PTR,   PTR,   PTR}},
		{"getresuid32",            INT,   3, {PTR,   PTR,   PTR}},
		{"setresgid32",            INT,   3, {PTR,   PTR,   PTR}},
		{"getresgid32",            INT,   3, {PTR,   PTR,   PTR}},
		{"chown32",                INT,   3, {STR,   INT,   INT}},
		{"setuid32",               INT,   1, {INT}},
		{"setgid32",               INT,   1, {INT}},
		{"setfsuid32",             INT,   1, {INT}},
		{"setfsgid32",             INT,   1, {INT}},
		{"pivot_root",             INT,   2, {STR,   STR}},
		{"mincore",                INT,   3, {ULONG, ULONG, STR}},
		{"madvise",                INT,   3, {ULONG, ULONG, INT}},
		{"getdents64",             INT,   3, {UINT,  PTR,   UINT}},
		{"fcntl64",                INT,   3, {UINT,  UINT,  ULONG}},
		{"NOT_IMPLEMENTED",        VOID,  0, {}},
		{"NOT_IMPLEMENTED",        VOID,  0, {}},
		{"gettid",                 INT,   0, {}},
		{"readahead",              LONG,  3, {INT,   LONG,  ULONG}},
		{"setxattr",               INT,   5, {STR,   STR,   PTR,   ULONG, INT}},
		{"lsetxattr",              INT,   5, {STR,   STR,   PTR,   ULONG, INT}},
		{"fsetxattr",              INT,   5, {INT,   STR,   PTR,   ULONG, INT}},
		{"getxattr",               LONG,  4, {STR,   STR,   PTR,   ULONG}},
		{"lgetxattr",              LONG,  4, {STR,   STR,   PTR,   ULONG}},
		{"fgetxattr",              LONG,  4, {INT,   STR,   PTR,   ULONG}},
		{"listxattr",              LONG,  3, {STR,   STR,   ULONG}},
		{"llistxattr",             LONG,  3, {STR,   STR,   ULONG}},
		{"flistxattr",             LONG,  3, {INT,   STR,   ULONG}},
		{"removexattr",            INT,   2, {STR,   STR}},
		{"lremovexattr",           INT,   2, {STR,   STR}},
		{"fremovexattr",           INT,   2, {INT,   STR}},
		{"tkill",                  INT,   2, {INT,   INT}},
		{"sendfile64",             ULONG, 4, {INT,   INT,   PTR,   ULONG}},
		{"futex",                  INT,   6, {PTR,   INT,   UINT,  PTR,   PTR,   UINT}},
		{"sched_setaffinity",      INT,   3, {INT,   UINT,  PTR}},
		{"sched_getaffinity",      INT,   3, {INT,   UINT,  PTR}},
		{"set_thread_area",        INT,   1, {PTR}},
		{"get_thread_area",        INT,   1, {PTR}},
		{"io_setup",               INT,   2, {UINT,  PTR}},
		{"io_destroy",             INT,   1, {ULONG}},
		{"io_getevents",           INT,   5, {ULONG, LONG,  LONG,  PTR,   PTR}},
		{"io_submit",              INT,   3, {ULONG, LONG,  PTR}},
		{"io_cancel",              INT,   3, {ULONG, PTR,   PTR}},
		{"fadvise64",              INT,   4, {INT,   LONG,  ULONG, INT}},
		{"NOT_IMPLEMENTED",        VOID,  0, {}},
		{"exit_group",             VOID,  1, {INT}},
		{"lookup_dcookie",         INT,   3, {ULONG, STR,   ULONG}},
		{"epoll_create",           INT,   1, {INT}},
		{"epoll_ctl",              INT,   4, {INT,   INT,   INT,   PTR}},
		{"epoll_wait",             INT,   4, {INT,   PTR,   INT,   INT}},
		{"remap_file_pages",       INT,   5, {ULONG, ULONG, ULONG, ULONG, ULONG}},
		{"set_tid_address",        LONG,  1, {PTR}},
		{"timer_create",           INT,   3, {INT,   PTR,   PTR}},
		{"timer_settime",          INT,   4, {INT,   INT,   PTR,   PTR}},
		{"timer_gettime",          INT,   2, {INT,   PTR}},
		{"timer_getoverrun",       INT,   1, {INT}},
		{"timer_delete",           INT,   1, {INT}},
		{"clock_settime",          INT,   2, {INT,   PTR}},
		{"clock_gettime",          INT,   2, {INT,   PTR}},
		{"clock_getres",           INT,   2, {INT,   PTR}},
		{"clock_nanosleep",        INT,   4, {INT,   INT,   PTR,   PTR}},
		{"statfs64",               INT,   3, {STR,   ULONG, PTR}},
		{"fstatfs64",              INT,   3, {UINT,  ULONG, PTR}},
		{"tgkill",                 INT,   3, {INT,   INT,   INT}},
		{"utimes",                 INT,   2, {STR,   PTR}},
		{"fadvise64_64",           INT,   4, {INT,   LONG,  LONG,  INT}},
		{"vserver",                VOID,  0, {}},
		{"mbind",                  LONG,  6, {ULONG, ULONG, ULONG, PTR,   ULONG, UINT}},
		{"get_mempolicy",          LONG,  5, {PTR,   PTR,   ULONG, ULONG, ULONG}},
		{"set_mempolicy",          LONG,  3, {INT,   PTR,   ULONG}},
		{"mq_open",                ULONG, 4, {STR,   INT,   UINT,  PTR}},
		{"mq_unlink",              INT,   1, {STR}},
		{"mq_timedsend",           INT,   5, {INT,   STR,   ULONG, UINT,  PTR}},
		{"mq_timedreceive",        LONG,  5, {INT,   STR,   ULONG, PTR,   PTR}},
		{"mq_notify",              INT,   2, {INT,   PTR}},
		{"mq_getsetattr",          INT,   3, {INT,   PTR,   PTR}},
		{"kexec_load",             LONG,  4, {ULONG, ULONG, PTR,   ULONG}},
		{"waitid",                 INT,   5, {INT,   INT,   PTR,   INT,   PTR}},
		{"NOT_IMPLEMENTED",        VOID,  0, {}},
		{"add_key",                INT,   5, {STR,   STR,   PTR,   ULONG, INT}},
		{"request_key",            INT,   4, {STR,   STR,   STR,   INT}},
		{"keyctl",                 LONG,  5, {INT,   ULONG, ULONG, ULONG, ULONG}},
		{"ioprio_set",             INT,   3, {INT,   INT,   INT}},
		{"ioprio_get",             INT,   2, {INT,   INT}},
		{"inotify_init",           INT,   0, {}},
		{"inotify_add_watch",      INT,   3, {INT,   STR,   UINT}},
		{"inotify_rm_watch",       INT,   2, {INT,   INT}},
		{"migrate_pages",          LONG,  4, {INT,   ULONG, PTR,   PTR}},
		{"openat",                 INT,   4, {INT,   STR,   INT,   UINT}},
		{"mkdirat",                INT,   3, {INT,   STR,   UINT}},
		{"mknodat",                INT,   4, {INT,   STR,   UINT,  UINT}},
		{"fchownat",               INT,   5, {INT,   STR,   UINT,  UINT,  INT}},
		{"futimesat",              INT,   3, {INT,   STR,   PTR}},
		{"fstatat64",              INT,   4, {INT,   STR,   PTR,   INT}},
		{"unlinkat",               INT,   3, {INT,   STR,   INT}},
		{"renameat",               INT,   4, {INT,   STR,   INT,   STR}},
		{"linkat",                 INT,   5, {INT,   STR,   INT,   STR,   INT}},
		{"symlinkat",              INT,   3, {STR,   INT,   STR}},
		{"readlinkat",             LONG,  4, {INT,   STR,   STR,   INT}},
		{"fchmodat",               INT,   3, {INT,   STR,   UINT}},
		{"faccessat",              INT,   3, {INT,   STR,   INT}},
		{"pselect6",               INT,   6, {INT,   PTR,   PTR,   PTR,   PTR,   PTR}},
		{"ppoll",                  INT,   5, {PTR,   UINT,  PTR,   PTR,   ULONG}},
		{"unshare",                INT,   1, {ULONG}},
		{"set_robust_list",        LONG,  2, {PTR,   ULONG}},
		{"get_robust_list",        LONG,  3, {INT,   PTR,   PTR}},
		{"splice",                 LONG,  6, {INT,   PTR,   INT,   PTR,   ULONG, UINT}},
		{"sync_file_range",        INT,   4, {INT,   LONG,  LONG,  UINT}},
		{"tee",                    LONG,  4, {INT,   INT,   ULONG, UINT}},
		{"vmsplice",               LONG,  4, {INT,   PTR,   ULONG, UINT}},
		{"move_pages",             LONG,  6, {INT,   ULONG, PTR,   PTR,   PTR,   INT}},
		{"getcpu",                 INT,   3, {PTR,   PTR,   PTR}},
		{"epoll_pwait",            INT,   6, {INT,   PTR,   INT,   INT,   PTR,   ULONG}},
		{"utimensat",              INT,   4, {INT,   STR,   PTR,   INT}},
		{"signalfd",               INT,   3, {INT,   PTR,   ULONG}},
		{"timerfd_create",         INT,   2, {INT,   INT}},
		{"eventfd",                INT,   1, {UINT}},
		{"fallocate",              INT,   4, {INT,   INT,   LONG,  LONG}},
		{"timerfd_settime",        INT,   4, {INT,   INT,   PTR,   PTR}},
		{"timerfd_gettime",        INT,   2, {INT,   PTR}},
		{"signalfd4",              INT,   4, {INT,   PTR,   ULONG, INT}},
		{"eventfd2",               INT,   2, {UINT,  INT}},
		{"epoll_create1",          INT,   1, {INT}},
		{"dup3",                   INT,   3, {UINT,  UINT,  INT}},
		{"pipe2",                  INT,   2, {PTR,   INT}},
		{"inotify_init1",          INT,   1, {INT}},
		{"preadv",                 LONG,  5, {ULONG, PTR,   ULONG, ULONG, ULONG}},
		{"pwritev",                LONG,  5, {ULONG, PTR,   ULONG, ULONG, ULONG}},
		{"rt_tgsigqueueinfo",      INT,   4, {INT,   INT,   INT,   PTR}},
		{"perf_event_open",        INT,   5, {PTR,   INT,   INT,   INT,   ULONG}},
		{"recvmmsg",               INT,   5, {INT,   PTR,   UINT,  UINT,  PTR}},
		{"fanotify_init",          INT,   2, {UINT,  UINT}},
		{"fanotify_mark",          INT,   5, {INT,   UINT,  ULONG, INT,   STR}},
		{"prlimit64",              INT,   4, {INT,   UINT,  PTR,   PTR}},
		{"name_to_handle_at",      INT,   5, {INT,   STR,   PTR,   PTR,   INT}},
		{"open_by_handle_at",      INT,   3, {INT,   PTR,   INT}},
		{"clock_adjtime",          VOID,  2, {INT,   PTR}},
		{"syncfs",                 INT,   1, {INT}},
		{"sendmmsg",               INT,   4, {INT,   PTR,   UINT,  UINT}},
		{"setns",                  INT,   2, {INT,   INT}},
		{"process_vm_readv",       LONG,  6, {INT,   PTR,   ULONG, PTR,   ULONG, ULONG}},
		{"process_vm_writev",      LONG,  6, {INT,   PTR,   ULONG, PTR,   ULONG, ULONG}},
		{"kcmp",                   INT,   5, {INT,   INT,   INT,   ULONG, ULONG}},
		{"finit_module",           INT,   3, {INT,   STR,   INT}},
		{"sched_setattr",          INT,   3, {INT,   PTR,   UINT}},
		{"sched_getattr",          INT,   4, {INT,   PTR,   UINT,  UINT}},
		{"renameat2",              INT,   5, {INT,   STR,   INT,   STR,   UINT}},
		{"seccomp",                INT,   3, {UINT,  UINT,  PTR}},
		{"getrandom",              LONG,  3, {STR,   ULONG, UINT}},
		{"memfd_create",           INT,   2, {STR,   UINT}},
		{"bpf",                    INT,   3, {INT,   PTR,   UINT}},
		{"execveat",               INT,   5, {INT,   STR,   ARRAY, ARRAY, INT}},
		{"socket",                 INT,   3, {INT,   INT,   INT}},
		{"socketpair",             INT,   4, {INT,   INT,   INT,   PTR}},
		{"bind",                   INT,   3, {INT,   PTR,   INT}},
		{"connect",                INT,   3, {INT,   PTR,   INT}},
		{"listen",                 INT,   2, {INT,   INT}},
		{"accept4",                INT,   4, {INT,   PTR,   PTR,   INT}},
		{"getsockopt",             INT,   5, {INT,   INT,   INT,   STR,   PTR}},
		{"setsockopt",             INT,   5, {INT,   INT,   INT,   STR,   INT}},
		{"getsockname",            INT,   3, {INT,   PTR,   PTR}},
		{"getpeername",            INT,   3, {INT,   PTR,   PTR}},
		{"sendto",                 LONG,  6, {INT,   PTR,   ULONG, UINT,  PTR,   INT}},
		{"sendmsg",                LONG,  3, {INT,   PTR,   UINT}},
		{"recvfrom",               LONG,  6, {INT,   PTR,   ULONG, UINT,  PTR,   PTR}},
		{"recvmsg",                LONG,  3, {INT,   PTR,   UINT}},
		{"shutdown",               INT,   2, {INT,   INT}},
		{"userfaultfd",            INT,   1, {INT}},
		{"membarrier",             INT,   2, {INT,   INT}},
		{"mlock2",                 INT,   3, {ULONG, ULONG, INT}},
		{"copy_file_range",        LONG,  6, {INT,   PTR,   INT,   PTR,   ULONG, UINT}},
		{"preadv2",                LONG,  6, {ULONG, PTR,   ULONG, ULONG, ULONG, INT}},
		{"pwritev2",               LONG,  6, {ULONG, PTR,   ULONG, ULONG, ULONG, INT}},
		{"pkey_mprotect",          INT,   4, {ULONG, ULONG, ULONG, INT}},
		{"pkey_alloc",             INT,   2, {ULONG, ULONG}},
		{"pkey_free",              INT,   1, {INT}},
		{"statx",                  INT,   5, {INT,   STR,   UINT,  UINT,  PTR}},
		{"arch_prctl",             INT,   2, {INT,   PTR}}
};

const t_syscall *find_syscall_by_id(uint64_t syscall_id, uint32_t arch) {
	if (arch == AUDIT_ARCH_X86_64 && syscall_id < sizeof(syscall_table_64) / sizeof(t_syscall))
		return &syscall_table_64[syscall_id];
	else if (arch == AUDIT_ARCH_I386 && syscall_id < sizeof(syscall_table_32) / sizeof(t_syscall))
		return &syscall_table_32[syscall_id];
	else
		return NULL;
}